spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: EScommunity

  datasource:
    url : ${DB_URL}
    username : ${DB_USER}
    password : ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      notify-keyspace-events: Ex

    elasticsearch:
      client:
        elasticsearch:
          uris: ${ES_URL}

  jpa:
    hibernate:
      ddl-auto: none #update

jwt:
  token:
    secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    s3:
      bucketName: ${S3_BUCKET_NAME}
